# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GitHub Actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-mock pytest-cov click
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - name: Generate coverage badge
        run: |
          total=$(grep total htmlcov/index.html -A 10000 | grep data-ratio -m 1 | grep -e [0-9][0-9]% -o)
          coverage=${total:0:-1}
          echo $coverage
          if [ $coverage -ge 83 ] ; then
            COLOR=brightgreen
          elif [ $coverage -ge 67 ] ; then
            COLOR=green
          elif [ $coverage -ge 50 ] ; then
            COLOR=yellowgreen
          elif [ $coverage -ge 33 ] ; then
            COLOR=yellow
          elif [ $coverage -ge 17 ] ; then
            COLOR=orange
          else
            COLOR=red
          fi
          badge=https://img.shields.io/badge/Coverage-${total}-${COLOR}
          wget -O badge-coverage.svg ${badge}
      - name: Publish coverage badge
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SAKURA_HOST }}
          username: ${{ secrets.SAKURA_USERNAME }}
          password: ${{ secrets.SAKURA_PASSWORD }}
          source: "badge-coverage.svg"
          target: ${{ secrets.SAKURA_TARGET }}
